### ISSUE TITLE
App crashes upon launch on iPad 8th Gen, 17.0, installed through TrollStore

### ISSUE THREAD

**Issue by C4ndyF1sh** [inyourwalls/Blossom#1]

**Comment by Nangjing** [comment]
iPad Pro 5th gen 17.0 also crashes

**Comment by inyourwalls** [comment]
Unfortunately I own only iPhone, so I can't test this on iPad. If someone is willing to share crash logs, I might fix this when I'm free.

**Comment by Nangjing** [comment]
> Unfortunately I own only iPhone, so I can't test this on iPad. If someone is willing to share crash logs, I might fix this when I'm free.

[Blossom-2024-12-21-153059.zip](https://github.com/user-attachments/files/18217708/Blossom-2024-12-21-153059.zip)
