### ISSUE TITLE
App not opening on iOS 17 beta iPhone A12+

### ISSUE THREAD

**Issue by Pirates0** [inyourwalls/Blossom#2]
I’ve tried everything thought maybe there are some conflicting apps. Not sure.

**Comment by inyourwalls** [comment]
I've tested it on stable 17.0. It's hard to say what causes the crash without the logs, try this version and let me know if it works
[1.0.3.tipa.zip](https://github.com/user-attachments/files/18221211/1.0.3.tipa.zip)

**Comment by Pirates0** [comment]
It worked perfectly you’re amazing  brohiem!
