### ISSUE TITLE
App doesn't crash anymore on iPad 8, 17.0 but iPadOS seems not to be allowing Live Wallpaper.

### ISSUE THREAD

**Issue by C4ndyF1sh** [inyourwalls/Blossom#3]
Would there be a way to overwrite it, making it working?

**Comment by inyourwalls** [comment]
Try making a random photo with "Live Photo" enabled, then tap on "Share" and tap on "Use as wallpaper". Then the main issue arrives with these live photos, is that there's a bug preventing some of them to be used (in the screenshot the icon below the message is crossed out). So keep trying with different photos, it's a stock bug as far as I know.
![image](https://github.com/user-attachments/assets/7cdb86cc-de54-4883-b488-087841d1ae9f)

**Comment by C4ndyF1sh** [comment]
@inyourwalls Ive tried many different Live Photos but none of them worked.

Luckily, I've found a working converting app: https://apps.apple.com/de/app/video-to-live-photos-maker/id1596786737

**Comment by C4ndyF1sh** [comment]
It only lets you allow 1 video to Live Photo converting for free though, will try to find a better app

**Comment by C4ndyF1sh** [comment]
Sadly, I couldn't find any other working app, tried over 10 different ones 😢

**Comment by inyourwalls** [comment]
I think live photos that are about 1.5 seconds long have the best probability to work. 3 second long photos don't work for me either half the time.

**Comment by C4ndyF1sh** [comment]
@inyourwalls The thing is, that I tried all of these apps with the same vid, which was 5 secs long

**Comment by inyourwalls** [comment]
That's not how it works, you need to make a live photo wallpaper, doesn't matter what is on it or how long is it. Then you configure lockscreen widgets, etc. Then you choose in app the actual 5 second video and it'll swap. If the duration/cropping is wrong it'll show you how to fix it using default photos app.

**Comment by C4ndyF1sh** [comment]
@inyourwalls The video is exactly 5.00 seconds long and I cropped it to the screen format of 5:4 (also tried with 4:5), but in both cases it didn't worked and showed me the guide to "fix it"

I noticed in the video that theres a "Wallpaper" option when cropping a video in the photos app, and I don't have this option

**Comment by inyourwalls** [comment]
Okay I'll remove this check in a few hours. Maybe that option is for iphone only.

**Comment by inyourwalls** [comment]
So, this update should allow you to set a video of any resolution now (though the last frame of it might look wrong, that's why the checks were there in the first place). Just make sure the video duration is exactly 5 seconds long. You can crop the resolution afterwards using some online video editor. Hopefully this will help you pinpoint the issue.

**Comment by C4ndyF1sh** [comment]
@inyourwalls Omg that fixed it

**Comment by C4ndyF1sh** [comment]
@inyourwalls Could you add the link of the app I used to Blossom or the GitHub readme somewhere? I am sure not only me has this bug

**Comment by inyourwalls** [comment]
Yeah it's in the releases page https://github.com/inyourwalls/Blossom/releases/tag/1.0.3. Thanks for testing though

**Comment by C4ndyF1sh** [comment]
@inyourwalls That is not what I meant though, I mean when putting any Live Photo as a wallpaper through the photos app which doesn't work

**Comment by inyourwalls** [comment]
Sure I'll add that

**Comment by C4ndyF1sh** [comment]
@inyourwalls Sorry for all the pings but there is still one small issue, when applying a new Live Photo as a background in blossom (with and without Loop on) it throws out this error message and blossom keeps infinitely loading when pressing it away till blossom is closed and reopened 

The new Live Photo wallpaper gets still applied though 


![image](https://github.com/user-attachments/assets/1ca647ee-f7dd-4fe8-8605-df31a0255f4e)

**Comment by inyourwalls** [comment]
Try the attached version below. If that doesn't work:

1. Make a new wallpaper
2. Open Filza so I can review the bug. I don't have iPad and that file might differ from iPhone. In Filza, navigate to /var/mobile/Containers/Data/Application/ (PosterBoard) /Library/Application Support/PRBPosterExtensionDataStore/ (id) /Extensions/com.apple.PhotosUIPrivate.PhotosPosterProvider/configurations/ (Your wallpaper UUID, to find out the correct one just navigate to each one and check the image file in them) /versions/0/contents/ (id) /output.layerStack and send the Contents.json file here

[Blossom.tipa.zip](https://github.com/user-attachments/files/18222458/Blossom.tipa.zip)

**Comment by C4ndyF1sh** [comment]
@inyourwalls That fixed it, is it supposed to respring the device after applying though?

**Comment by inyourwalls** [comment]
I've ran into some weird bugs without respring, the wallpaper behaved strangely.

**Comment by C4ndyF1sh** [comment]
I think you can close this issue again
