### ISSUE TITLE
live wallpaper becomes static and cannot be used normally

### ISSUE THREAD

**Issue by Yilun0823** [inyourwalls/Blossom#4]
At first, the wallpaper was replaced successfully, and it was successfully changed to live wallpaper. However, after changing a video, the live wallpaper became abnormal and the wallpaper became static. I tried many times but still couldn't do it. Please fix the problem. Thank you
 (using the latest 1.0.4 version)

**Comment by C4ndyF1sh** [comment]
Try this ![image](https://github.com/user-attachments/assets/f0a1fbbf-f3d2-4808-b067-b64f7531e3bf)

**Comment by Yilun0823** [comment]
It has been repaired successfully. Thank you.
